version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

    pre_build:
      command:
        - echo In the pre_build phase..
        - mvn test

    build:
      command:
        - echo Build started on `date`
        - mvn package
        
    post_build:
      command:
        - echo Build completed on `date`

artifacts:
  files:
    - target/*.war
  discard-path: yes